import express from 'express';
import signupRouter from '../routes/signUp.js';
import signupRequestRouter from '../routes/signupRequests.js';
import loginRouter from '../routes/login.js';
import sessionRouter from '../routes/session.js';
import sessionRequestRouter from '../routes/sessionRequests.js';
import userRouter from '../routes/user.js';
import candidateRouter from '../routes/candidate.js';
import voteRouter from '../routes/vote.js';
import optionRouter from '../routes/option.js';
export default function (app) {
  app.use(express.json());
  app.use("/votex/api/signup", signupRouter);
  app.use("/votex/api/signup-requests", signupRequestRouter);
  app.use("/votex/api/login", loginRouter);
  app.use("/votex/api/sessions", sessionRouter);
  app.use("/votex/api/sessionRequests",sessionRequestRouter);
  app.use("/votex/api/users", userRouter);
  app.use("/votex/api/sessions/:sessionId/vote", voteRouter);
  app.use("/votex/api/sessions/:sessionId/candidate", candidateRouter);
  app.use("/votex/api/sessions/:sessionId/option", optionRouter);
};
